CREATE TABLE Livraria (
CNPJ VARCHAR(14) NOT NULL,
Telefone VARCHAR(11),
Cidade VARCHAR(50) NOT NULL,
Estado VARCHAR(50) NOT NULL,
CONSTRAINT PK_CNPJ PRIMARY KEY(CNPJ)
);

CREATE TABLE Livro (
ISBN VARCHAR(13) NOT NULL,
Encadernacao VARCHAR(20),
Peso VARCHAR(10),
Altura VARCHAR(10),
Comprimento VARCHAR(10),
Editora VARCHAR(50),
Paginas INT(5) NOT NULL,
Edicao INT(3) NOT NULL,
FaixaEtaria INT(3),
PaisDeProducao VARCHAR(50),
Ano INT(4),
Idioma VARCHAR(20) NOT NULL,
Assunto VARCHAR(50) NOT NULL,
Titulo VARCHAR(50) NOT NULL,
Capa VARCHAR(50),
Genero VARCHAR(50) NOT NULL,
Preco INT,
Autor VARCHAR(100) NOT NULL,
CONSTRAINT PK_ISBN PRIMARY KEY(ISBN)
);

CREATE TABLE Livraria_Livro (
ISBN VARCHAR(13) NOT NULL,
CNPJ VARCHAR(14) NOT NULL,
CONSTRAINT FK_ISBN FOREIGN KEY(ISBN) REFERENCES Livro (ISBN),
CONSTRAINT FK_CNPJ FOREIGN KEY(CNPJ) REFERENCES Livraria (CNPJ)
);

CREATE TABLE Administrador(
NOME VARCHAR(50) NOT NULL,
CNPJ VARCHAR(14) NOT NULL,
SENHA VARCHAR(50) NOT NULL,
CONSTRAINT PK_NOME PRIMARY KEY(NOME),
CONSTRAINT FK_CNPJ_ADM FOREIGN KEY(CNPJ) REFERENCES Livraria (CNPJ)
);

